### ISSUE TITLE
Nome do repositório errado.

### ISSUE THREAD

**Issue by pwebufersa** [mariali51/pweb_2020.2_mariaLidijane#2]
O nome do repositório está errado!

Deve ser **pweb**_2020.2_maria**L**idijane.

Fico esperando você arrumar.

**Comment by mariali51** [comment]
Já concertei o nome professor

**Comment by pwebufersa** [comment]
Ainda tá errado...:

pwe**b**_2020.2_mariaLidijane

**Comment by mariali51** [comment]
Em dom, 14 de mar de 2021 19:00, Programação WEB - UFERSA Angicos <
***@***.***> escreveu:
