### ISSUE TITLE
Maiusculas e minúsculas

### ISSUE THREAD

**Issue by pwebufersa** [mariali51/pweb_2020.2_mariaLidijane#4]
Os nomes das pastas ainda estão bagunçados.

**Comment by pwebufersa** [comment]
Arrumei, cansei de esperar.

**Comment by mariali51** [comment]
Prezado professor peço desculpas, pois agora que vi o seu email. Porque o
aplicativo do meu gmail estava parando de funcionar continuamente e tal
problema ainda está acontecendo. Agora que estou conseguindo falar pelo o
pc..

Atenciosamente: Maria Lidijane

Em ter., 23 de mar. de 2021 às 22:17, Programação WEB - UFERSA Angicos <
***@***.***> escreveu:
